### ISSUE TITLE
access inbox management

### ISSUE THREAD

**Issue by elf-pavlik** [janeirodigital/sai-impl-service#71]
#66 doesn't have full handling of access inbox

### TODO

* [ ] push notification should include `interop:grantedBy`
* [ ] once agent registration is created, remove the receipt from the inbox
* [ ] auto-delete receipts from all agents that already have social agent registration
* [ ] only allow one access receipt per agent in the inbox, if another one arrived delete it silently
* [ ] advanced: detect spam and blacklist sender in ACR

**Comment by elf-pavlik** [comment]
There could be also an option to remove access inbox all together from the spec: https://github.com/solid/data-interoperability-panel/issues/280
